# Generated by Django 4.2.20 on 2025-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('mode', models.CharField(choices=[('rag', 'RAG'), ('gpt4', 'GPT-4')], max_length=10)),
                ('response', models.TextField()),
                ('response_time', models.FloatField()),
                ('cost', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
